import { App } from "./app";

new App().server.listen(3000);

const { PrismaClient } = require('@prisma/client');
const XLSX = require('xlsx');
const prisma = new PrismaClient();

const readExcel = (filePath: string) => {
  const workbook = XLSX.readFile(filePath);
  const sheetName = workbook.SheetNames[0];
  const sheet = workbook.Sheets[sheetName];
  return XLSX.utils.sheet_to_json(sheet);
};

const insertData = async (data: any) => {
  for (const row of data) {
    await prisma.familia.create({
      data: {
        municipio: row.MUNICIPIO,
        nacionalidade: row.NACIONALIDADE,
        situacaoNacionalidade: row.SITUACAO_NACIONALIDADE,
        sexo: row.SEXO,
        identidadeGenero: row.IDENTIDADE_GENERO,
        orientacaoSexual: row.ORIENTACAO_SEXUAL,
        raca: row.RACA,
        povoIndigena: row.POVO_INDIGENA,
        dominaPortugues: row.DOMINA_PORTUGUES,
        dominaIngles: row.DOMINA_INGLES,
        dominaFrances: row.DOMINA_FRANCES,
        dominaEspanhol: row.DOMINA_ESPANHOL,
        dominaAlemao: row.DOMINA_ALEMAO,
        dominaLinguaIndigenaMaterna: row.DOMINA_LINGUA_INDIGENA_MATERNA,
        dominaMaisLinguasIndigenas: row.DOMINA_MAIS_LINGUAS_INDIGENAS,
        estadoCivil: row.ESTADO_CIVIL,
        idadeChefe: row.IDADE_CHEFE,
        ondeMora: row.ONDE_MORA,
        tempoResidencia: row.TEMPO_RESIDENCIA,
        localizacaoMoradia: row.LOCALIZACAO_MORADIA,
        alvenaria: row.ALVENARIA,
        madeiraTaquara: row.MADEIRA_TAQUARA,
        aguaTratadaEncanada: row.AGUA_TRATADA_ENCANADA,
        energiaEletrica: row.ENERGIA_ELETRICA,
        asfaltoCalcamento: row.ASFALTO_CALCAMENTO,
        coletaLixo: row.COLETA_LIXO,
        lageForro: row.LAGE_FORRO,
        esgoto: row.ESGOTO,
        iluminacaoPublica: row.ILUMINACAO_PUBLICA,
        qtdBanheiros: row.QTD_BANHEIROS,
        banheiroComBarrasSeguranca: row.BANHEIRO_COM_BARRAS_SEGURANCA,
        qtdTvs: row.QTD_TVS,
        qtdRadios: row.QTD_RADIOS,
        qtdComputadores: row.QTD_COMPUTADORES,
        possuiMaquinaLavar: row.POSSUI_MAQUINA_LAVAR,
        qtdGeladeira: row.QTD_GELADEIRA,
        temFreezer: row.TEM_FREEZER,
        qtdTelefoneCelular: row.QTD_TELEFONE_CELULAR,
        temAcessoInternet: row.TEM_ACESSO_INTERNET,
        temTvAssinatura: row.TEM_TV_ASSINATURA,
        placaFotovoltaica: row.PLACA_FOTOVOLTAICA,
        qtdAutomovelProprio: row.QTD_AUTOMOVEL_PROPRIO,
        qtdMotocicletaPropria: row.QTD_MOTOCICLETA_PROPRIA,
        qtdBicicletaEletrica: row.QTD_BICICLETA_ELETRICA,
        qtdBicicleta: row.QTD_BICICLETA,
        deslocaAutomovelProprio: row.DESLOCA_AUTOMOVEL_PROPRIO,
        deslocaMotocicletaPropria: row.DESLOCA_MOTOCICLETA_PROPRIA,
        deslocaBicicletaEletrica: row.DESLOCA_BICICLETA_ELETRICA,
        deslocaBicicleta: row.DESLOCA_BICICLETA,
        deslocaOnibusUrbano: row.DESLOCA_ONIBUS_URBANO,
        deslocaVeiculoAplicativo: row.DESLOCA_VEICULO_APLICATIVO,
        deslocaAPe: row.DESLOCA_A_PE,
        tempoDeslocamentoTrabalho: row.TEMPO_DESLOCAMENTO_TRABALHO,
        qtdPessoas: row.QTD_PESSOAS,
        qtdCriancas0a5: row.QTD_CRIANCAS_0_A_5,
        qtdIdosos: row.QTD_IDOSOS,
        qtdDeficientes: row.QTD_DEFICIENTES,
        cuidadosIdosoDeficiente: row.CUIDADOS_IDOSO_DEFICIENTE,
        buscaServicoSus: row.BUSCA_SERVICO_SUS,
        recebeVisitaAgente: row.RECEBE_VISITA_AGENTE,
        vacinasCriancasCompleto: row.VACINAS_CRIANCAS_COMPLETO,
        vacinaAdultosCompleto: row.VACINA_ADULTOS_COMPLETO,
        gestantes: row.GESTANTES,
        mulher10a17ComFilhos: row.MULHER_10_A_17_COM_FILHOS,
        criancas0a5Matriculadas: row.CRIANCAS_0_A_5_MATRICULADAS,
        criancas6a14Matriculadas: row.CRIANCAS_6_A_14_MATRICULADAS,
        adolescentes15a17Matriculados: row.ADOLESCENTES_15_A_17_MATRICULADOS,
        membroBeneficiarioProgramaHabitacao: row.MEMBRO_BENEFICIARIO_PROGRAMA_HABITACAO,
        adolescenteCumprindoMedidas: row.ADOLESCENTE_CUMPRINDO_MEDIDAS,
        adolescentePrivadoLiberdade: row.ADOLESCENTE_PRIVADO_LIBERDADE,
        membroSituacaoCarcere: row.MEMBRO_SITUACAO_CARCERE,
        membroUsoEntorpecente: row.MEMBRO_USO_ENTORPECENTE,
        membroAlcoolista: row.MEMBRO_ALCOOLISTA,
        membroHipertenso: row.MEMBRO_HIPERTENSO,
        membroDiabetico: row.MEMBRO_DIABETICO,
        membroProblemaVisao: row.MEMBRO_PROBLEMA_VISAO,
        utilizaCras: row.UTILIZA_CRAS,
        utilizaCreas: row.UTILIZA_CREAS,
        utilizaCentroConvivencia: row.UTILIZA_CENTRO_CONVIVENCIA,
        utilizaSadpi: row.UTILIZA_SADPI,
        utilizaSadpd: row.UTILIZA_SADPD,
        utilizaSadc0a6: row.UTILIZA_SADC_0_A_6,
        utilizaSrahrpd: row.UTILIZA_SRAHRPD,
        naoUtilizaSuas: row.NAO_UTILIZA_SUAS,
        recebeBolsaFamilia: row.RECEBE_BOLSA_FAMILIA,
        recebeMaisSocial: row.RECEBE_MAIS_SOCIAL,
        recebeBpc: row.RECEBE_BPC,
        recebeValeGas: row.RECEBE_VALE_GAS,
        naoRecbeBeneficio: row.NAO_RECBE_BENEFICIO,
        unidadeAcolhimentoIdoso: row.UNIDADE_ACOLHIMENTO_IDOSO,
        unidadeAcolhimentoDeficiente: row.UNIDADE_ACOLHIMENTO_DEFICIENTE,
        unidadeAcolhimentoCriancaAdolescente: row.UNIDADE_ACOLHIMENTO_CRIANCA_ADOLESCENTE,
        naoViveUnidadeAcolhimento: row.NAO_VIVE_UNIDADE_ACOLHIMENTO,
        qtdCriancas6a9: row.QTD_CRIANCAS_6_A_9,
        qtdCriancas10a14: row.QTD_CRIANCAS_10_A_14,
        qtdCriancas15a17: row.QTD_CRIANCAS_15_A_17,
        qtdMulher10a17: row.QTD_MULHER_10_A_17,
        anosEstudo: row.ANOS_ESTUDO,
        maiores15NaoEstudamTabalham: row.MAIORES_15_NAO_ESTUDAM_TABALHAM,
        naoEstudaTrabalhaProcurandoEmprego: row.NAO_ESTUDA_TRABALHA_PROCURANDO_EMPREGO,
        naoEstudaTrabalhaCuidaFilhos: row.NAO_ESTUDA_TRABALHA_CUIDA_FILHOS,
        naoEstudaTrabalhaDomestico: row.NAO_ESTUDA_TRABALHA_DOMESTICO,
        estudandoNoMomento: row.ESTUDANDO_NO_MOMENTO,
        motivoVoltarEstudar: row.MOTIVO_VOLTAR_ESTUDAR,
        maiorInstrucaoFamilia: row.MAIOR_INSTRUCAO_FAMILIA,
        naoSabeLerEscrever: row.NAO_SABE_LER_ESCREVER,
        meioAmbiente: row.MEIO_AMBIENTE,
        aidsDst: row.AIDS_DST,
        racismoDiscriminacao: row.RACISMO_DISCRIMINACAO,
        discriminacaoMulher: row.DISCRIMINACAO_MULHER,
        discriminacaoHomossexuais: row.DISCRIMINACAO_HOMOSEXUAIS,
        discriminacaoEtaria: row.DISCRIMINACAO_ETARIA,
        discriminacaoReligiosa: row.DISCRIMINACAO_RELIGIOSA,
        desigualdadeSocial: row.DESIGUALDADE_SOCIAL,
        fomePobreza: row.FOME_POBREZA,
        favelasMoradia: row.FAVELAS_MORADIA,
        drogasAlcoolismo: row.DROGAS_ALCOOLISMO,
        violenciaAssassinatos: row.VIOLENCIA_ASSASSINATOS,
        violenciaRuralConflitos: row.VIOLENCIA_RURAL_CONFLITOS,
        situacaoEconomica: row.SITUACAO_ECONOMICA,
        saudePrecaria: row.SAUDE_PRECARIA,
        educacaoPrecaria: row.EDUCACAO_PRECARIA,
        assistenciaPrecaria: row.ASSISTENCIA_PRECARIA,
        segurancaPrecaria: row.SEGUURANCA_PRECARIA,
        ausenciaEsgotoColeta: row.AUSENCIA_ESGOTO_COLETA,
        ausenciaAsfalto: row.AUSENCIA_ASFALTO,
        enchentesDesastres: row.ENCHENTES_DESASTRES,
        recebeCestaAlimentosGoverno: row.RECEBE_CESTA_ALIMENTOS_GOVERNO,
        recebeCestaAlimentosFunai: row.RECEBE_CESTA_ALIMENTOS_FUNAI,
        recebeCestaAlimentosConab: row.RECEBE_CESTA_ALIMENTOS_CONAB,
        recebeCestaAlimentosPrefeitura: row.RECEBE_CESTA_ALIMENTOS_PREFEITURA,
        recebeCestaAlimentosOng: row.RECEBE_CESTA_ALIMENTOS_ONG,
        naoRecebeCestaAlimentos: row.NAO_RECEBE_CESTA_ALIMENTOS,
        preferenciaCestaAlimentos: row.PREFERENCIA_CESTA_ALIMENTOS,
        baixoConsumoArroz: row.BAIXO_CONSUMO_ARROZ,
        baixoConsumoFeijao: row.BAIXO_CONSUMO_FEIJAO,
        baixoConsumoSal: row.BAIXO_CONSUMO_SAL,
        baixoConsumoMacarrao: row.BAIXO_CONSUMO_MACARRAO,
        baixoConsumoOleo: row.BAIXO_CONSUMO_OLEO,
        baixoConsumoAcucar: row.BAIXO_CONSUMO_ACUCAR,
        baixoConsumoFuba: row.BAIXO_CONSUMO_FUBA,
        baixoConsumoLeite: row.BAIXO_CONSUMO_LEITE,
        baixoConsumoCharque: row.BAIXO_CONSUMO_CHARQUE,
        baixoConsumoFarinha: row.BAIXO_CONSUMO_FARINHA,
        quantosDiasConsomeCesta: row.QUANTOS_DIAS_CONSOME_CESTA,
        gostariaNaCestaErva: row.GOSTARIA_NA_CESTA_ERVA,
        gostariaNaCestaCafe: row.GOSTARIA_NA_CESTA_CAFE,
        gostariaNaCestaCanjica: row.GOSTARIA_NA_CESTA_CANJICA,
        gostariaNaCestaArroz: row.GOSTARIA_NA_CESTA_ARROZ,
        gostariaNaCestaFeijao: row.GOSTARIA_NA_CESTA_FEIJAO,
        gostariaNaCestaSal: row.GOSTARIA_NA_CESTA_SAL,
        gostariaNaCestaMacarrao: row.GOSTARIA_NA_CESTA_MACARRAO,
        gostariaNaCestaOleo: row.GOSTARIA_NA_CESTA_OLEO,
        gostariaNaCestaAcucar: row.GOSTARIA_NA_CESTA_ACUCAR,
        gostariaNaCestaFuba: row.GOSTARIA_NA_CESTA_FUBA,
        gostariaNaCestaLeite: row.GOSTARIA_NA_CESTA_LEITE,
        gostariaNaCestaCharque: row.GOSTARIA_NA_CESTA_CHARQUE,
        gostariaNaCestaFarinha: row.GOSTARIA_NA_CESTA_FARINHA,
        possuiRoca: row.POSSUI_ROCA,
        gostariaDeTerRoca: row.GOSTARIA_DE_TER_ROCA,
        cultivaMandioca: row.CULTIVA_MANDIOCA,
        cultivaMilho: row.CULTIVA_MILHO,
        cultivaMelao: row.CULTIVA_MELAO,
        cultivaAbobora: row.CULTIVA_ABOBORA,
        cultivaCana: row.CULTIVA_CANA,
        cultivaFeijao: row.CULTIVA_FEIJAO,
        cultivaBatata: row.CULTIVA_BATATA,
        possuiHorta: row.POSSUI_HORTA,
        gostariaDeTerHorta: row.GOSTARIA_DE_TER_HORTA,
        possuiHoraParceria: row.POSSUI_HORA_PARCEIRIA,
        naoCriaAnimais: row.NAO_CRIA_ANIMAIS,
        criaAves: row.CRIA_AVES,
        criaBovinos: row.CRIA_BOVINOS,
        criaSuinos: row.CRIA_SUINOS,
        trabalhaAgricultura: row.TRABALHA_AGRICULTURA,
        trabalhaIndustria: row.TRABALHA_INDUSTRIA,
        trabalhaConstrucaoCivil: row.TRABALHA_CONSTRUCAO_CIVIL,
        trabalhaSetorServicos: row.TRABALHA_SETOR_SERVICOS,
        trabalhaFuncionarioPublico: row.TRABALHA_FUNCIONARIO_PUBLICO,
        trabalhaPlProfessorTecnico: row.TRABALHA_PL_PROFESSOR_TECNICO,
        trabalhaForaAtividadesInformais: row.TRABALHA_FORA_ATIVIDADES_INFORMAIS,
        trabalhaDomestico: row.TRABALHA_DOMESTICO,
        trabalhaCasaInformal: row.TRABALHA_CASA_INFORMAL,
        trabalhaNoLar: row.TRABALHA_NO_LAR,
        naoTrabalha: row.NAO_TRABALHA,
        possuiCarteiraAssinada: row.POSSUI_CARTEIRA_ASSINADA,
        balcaoEmpregosNaCidade: row.BALCAO_EMPREGOS_NA_CIDADE,
        somaRenda: row.SOMA_RENDA,
        qtdCriancasAdolescentesTrabalham: row.QUANTIDADE_CRIANCAS_ADOLESCENTES_TRABALHAM
      },
    });
  }
};

const main = async () => {
  const data = readExcel('C:/Users/adria/Documents/GitHub/MSgraph/dados_ms_graph.xlsx');
  await insertData(data);
  console.log('Dados importados com sucesso!');
};

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
